# Generated by Django 6.0.5 on 2026-07-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_categorie_category_alter_listing_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
