# Generated by Django 6.0.5 on 2026-07-19 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_category_listing_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='category_id',
            new_name='category',
        ),
    ]
